### ISSUE TITLE
sometimes things work in dartium but not after compiling to javascript

### ISSUE THREAD

**Issue by kasperpeulen** [MikeMitterer/dart-material-design-lite#17]
I noticed this a couple of times, that things work when I'm playing around in dartium, but when I compile to javascript, it doesn't work anymore.

I guess I do something wrong, but I would prefer it that if I do something wrong, it also doesn't work in dartium, or even better, that I get an error message from the analyzer, see this gif:

![](http://i.imgur.com/H5CqOmV.gif)

to reproduce: https://github.com/kasperpeulen/bugs/tree/master/dart-material-design-lite%2317

**Comment by MikeMitterer** [comment]
Adding '@MdlComponentModel' does the trick! ;-)

``` dart
@MdlComponentModel
class MyDialog extends MaterialDialog {

  MyDialog() : super(new DialogConfig());

  onNo() => close(MdlDialogStatus.NO);
  onYes() => close(MdlDialogStatus.YES);

  String template = '''
  <div class="mdl-dialog">
  <div class="mdl-dialog__content">
    <p>Will this work ... ?</p>
  </div>
  <div class="mdl-dialog__actions">
    <button class="mdl-button mdl-js-button" data-mdl-click="onNo()">No</button>
    <button class="mdl-button mdl-js-button" data-mdl-click="onYes()">Yes</button>
  </div>
</div>
  ''';
}
```

**Comment by MikeMitterer** [comment]
Maybe you want to know why this is necessary ;-) - If a component acts as data-model then the mirror-system needs to know where/what to search. @MdlComponentModel avoids JS name mangling and because of this - the JS part is able to find the right class (object!)
