### ISSUE TITLE
version 1.3.2 is 32 mb ?

### ISSUE THREAD

**Issue by kasperpeulen** [MikeMitterer/dart-material-design-lite#18]
version 1.3.2 is 32 mb, I don't understand why this package is super big. I'm not able to get this package at my windows machine, because it takes too long to download...

> Timed out after 30.0s while downloading https://pub.dartlang.org/packages/mdl/versions/1.3.2.tar.gz.
> This is likely a transient error. Please try again later

**Comment by sethladd** [comment]
Can you open a bug for pub about the 30 second time out? We should be able
to download this package. Thanks!

**Comment by kasperpeulen** [comment]
@sethladd 

was looking at the pub commits, and this seems fixed a couple of days ago :)
https://github.com/dart-lang/pub/commit/e47ecbc74d6b62a5fe5c9d00029b15a62e0642b6

maybe the reason I don't have troubles with this at mac, is because I use the latest dev channel from brew at mac. At windows I use the latest version of chocolatey which is 1.11.1.

**Comment by sethladd** [comment]
If the issue pops up again, please let us know.

**Comment by MikeMitterer** [comment]
@sethladd Thanks!
