### ISSUE TITLE
Recommendations to improve adoption of the library

### ISSUE THREAD

**Issue by andresaraujo** [MikeMitterer/dart-material-design-lite#19]
Hi @MikeMitterer , 

I have been watching closely the evolution of the MDL for Dart/JS and I think there are few things that could help the adoption of the library.
##### Recommendations:
- **Quickstart should be easy to find and should be the same in README's repo and MDL site.** Its confusing to have different quickstart in the readme and in the site.
- **Setup of MDL for Dart should be as easy as MDL for JS.** In the JS version you only need to add a link to the CSS and JS files, the dart version starts with stagedive which confuses new users. 

Most of the MDL users want the MDL look and feel that the library provides out of the box.
- **Stagedive.** Rename Stagedive section to "Stagedive Support", move it below the quickstart, add brief explanation of what stagedive is and a link to its pub/repo.
- **Add a section of differences/advantages of using MDL for Dart compared to JS version.** 

I'm interested to hear what you think. Nice work BTW

**Comment by MikeMitterer** [comment]
I'm working on a new "Homepage" for material-design-lite. This page should concentrate all (most???) of the thing you mentioned. + Thanks for your input / help! 

![screenshot-1829](https://cloud.githubusercontent.com/assets/116654/9107261/4259b0e2-3c26-11e5-9e54-f828548b17bc.png)

**Comment by kasperpeulen** [comment]
Looks awesome :D @MikeMitterer

**Comment by andresaraujo** [comment]
Yeah it looks great!

**Comment by MikeMitterer** [comment]
What do you think? I've launched the new site yesterday...
http://www.material-design-lite.pub/

**Comment by jwashin** [comment]
Nice! I have a slow(er) connection, so pub times-out after 30 seconds if I try to get mdl directly through the usual dart methods. This makes mdl difficult to try out. As a work-around, I downloaded the .tar.gz file from pub using a web browser and extracted it into ~/.pub-cache/hosted/pub.dartlang.org/ . Hope this helps anyone else with a slow(er) connection.

**Comment by zoechi** [comment]
AFAIK this was changed recently. Pub shouldn't time out anymore on slow connections. I don't know with which Dart version that change will be shipped.
