### ISSUE TITLE
TextAreaElement' is not a subtype of type 'InputElement' 

### ISSUE THREAD

**Issue by giolaq** [MikeMitterer/dart-material-design-lite#23]
Calling a change on a textarea generates

Exception: Uncaught Error: type 'TextAreaElement' is not a subtype of type 'InputElement' in type cast.

  /// Update text field value.
    void change(final String value) {
        if (value != null && value != _relaxedInput.value) {

```
        int selStart = (_relaxedInput as dom.InputElement).selectionStart;
        int selEnd = (_relaxedInput as dom.InputElement).selectionStart;

        _relaxedInput.value = value;

        (_relaxedInput as dom.InputElement).setSelectionRange(selStart,selEnd);
    }

    _updateClasses();
}
```

**Comment by MikeMitterer** [comment]
Sorry - _relaxedInput was not as relaxed as expected. Thanks for your report!
