### ISSUE TITLE
Use the new Dart wordmark?

### ISSUE THREAD

**Issue by sethladd** [MikeMitterer/dart-material-design-lite#26]
Hi,

Can we ask that the homepage for Dart MDL use the new Dart wordmark? Image is here: https://github.com/dart-lang/logos/blob/master/logos_and_wordmarks/dart-logo-wordmark.png

Looks like the homepage is using the old version:

![screen shot 2015-11-02 at 9 14 08 am](https://cloud.githubusercontent.com/assets/5479/10888612/1989a4c2-8142-11e5-9f1a-e800d7f4fec6.png)

Thanks!

**Comment by MikeMitterer** [comment]
Changed! Thank you!
http://www.material-design-lite.pub/
