### ISSUE TITLE
Make copyright notice at the top of library not a doc comment

### ISSUE THREAD

**Issue by kevmoo** [MikeMitterer/dart-material-design-lite#27]
See https://www.dartdocs.org/documentation/mdl/1.5.1/index.html

Remove the 2nd `*` so this is just a normal comment – not a doc comment.

``` dart
/**
 * Copyright (c) 2015, Michael Mitterer (office@mikemitterer.at),
 * IT-Consulting and Development Limited.
 * ...
 */
```

**Comment by MikeMitterer** [comment]
Thanks!!!!

**Comment by kevmoo** [comment]
Thank you! :metal:

**Comment by kevmoo** [comment]
FYI: you didn't have to remove the copyright blocks – just the second \* in the first line.

...wanted to make sure that was clear. That's the difference between a code comment and a doc comment

**Comment by MikeMitterer** [comment]
Yea - thats exactly what I did. (or at least meant ;-))
