### ISSUE TITLE
class="mdl-textfield__error" prevents my error message from being displayed 

### ISSUE THREAD

**Issue by st-clair-clarke** [MikeMitterer/dart-material-design-lite#28]
Hi Mike,
Could you please take a look at this link [https://github.com/jwashin/angular2-rbi-dart/issues/2](https://github.com/jwashin/angular2-rbi-dart/issues/2) for me. class="mdl-textfield__error" is preventing my errors in a Dart Angular2 application. I am using [angular2_rbi](https://pub.dartlang.org/packages/angular2_rbi) that wraps your mdl package.

Thanks

**Comment by MikeMitterer** [comment]
Solved - see link above.
