### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by codetdq** [MikeMitterer/dart-material-design-lite#32]
Hi. I got this output when building a simple example:

> /usr/lib/dart/bin/pub build --mode=debug
> Loading source assets...
> Loading dart_to_js_script_rewriter and di transformers...
> Building untitled...
> [Info from Dart2JS]:
> Compiling untitled|web/main.dart...
> [Warning from Dart2JS]:
> web/main.dart:
> 496 methods retained for use by dart:mirrors out of 3909 total methods (13%).
> [Info from Dart2JS on untitled|web/main.dart]:
> packages/mdl/mdlapplication.dart:25:1:
> Import of 'dart:mirrors'.
> import 'dart:mirrors';
> ^^^^^^^^^^^^^^^^^^^^^^
> [Info from Dart2JS on untitled|web/main.dart]:
> packages/mdl/mdldirective.dart:23:1:
> Import of 'dart:mirrors'.
> import 'dart:mirrors';
> ^^^^^^^^^^^^^^^^^^^^^^
> [Info from Dart2JS on untitled|web/main.dart]:
> packages/mustache/src/renderer.dart:4:1:
> Import of 'dart:mirrors'.
> import 'dart:mirrors';
> ^^^^^^^^^^^^^^^^^^^^^^
> [Info from Dart2JS on untitled|web/main.dart]:
> packages/mdl/mdltemplate.dart:23:1:
> Import of 'dart:mirrors'.
> import 'dart:mirrors';
> ^^^^^^^^^^^^^^^^^^^^^^
> [Info from Dart2JS]:
> Took 0:00:23.471270 to compile untitled|web/main.dart.
> Could not find asset mdl|lib/_templates/article/manifest.yaml.
> package:pub/src/barback/pub_package_provider.dart 110  PubPackageProvider._assertExists
> package:pub/src/barback/pub_package_provider.dart 104  PubPackageProvider.getAsset.<async>
> This is an unexpected error. Please run
> 
> ```
> pub --trace build --mode=debug
> ```
> 
> and include the logs in an issue on https://github.com/dart-lang/pub/issues/new

**Comment by MikeMitterer** [comment]
Sorry for the late response. Just tried it with mdl_animation-Sample in v2.1.2 - works.
