### ISSUE TITLE
File upload & date picker components

### ISSUE THREAD

**Issue by nni123** [MikeMitterer/dart-material-design-lite#43]
Any plans to create file upload & date picker components? I am new to dart so checking if it is compatible with angular dart 4.

Thanks

**Comment by MikeMitterer** [comment]
Date- and Time-Picker is coming. I think next week.

**Comment by MikeMitterer** [comment]
Here you have it: http://styleguide.material-design-lite.pub/#/dialog (v2.1.2)

**Comment by nni123** [comment]
Thanks for Date Picker. 

Any info on File Upload component.

**Comment by MikeMitterer** [comment]
No not at the moment. I have one in my internal repo... But first I want to remove mirrors from mdl. The next step is to publish more components.
