### ISSUE TITLE
Format code with dartfmt tool

### ISSUE THREAD

**Issue by andresaraujo** [MikeMitterer/dart-material-design-lite#5]
To be easier to add contributions, the project should make use of the [dartfmt](https://www.dartlang.org/tools/dartfmt/)

**Comment by MikeMitterer** [comment]
Sorry - but no. I don't agree with quite a few of their definitions.

**Comment by kasperpeulen** [comment]
I kind of agree with @andresaraujo, to be honest, would make it easier and more inviting to continue. What is your problem with dart fmt? I think for an open source dart project, dart fmt makes the most sense...

**Comment by MikeMitterer** [comment]
Just to show two of my main concerns + this is more a "Google-Format-Thing" (their internal styleguide)
They indent 2 chars and they have a line-break on col 80.

I have two screens one with 2560x and the other one with 1920x res and Google wants me to set a max width of 80chars - sorry no! This made sense 10 years ago but not today.

![screenshot-1830](https://cloud.githubusercontent.com/assets/116654/9107839/bc0107a2-3c2a-11e5-84ca-db0ab7e9469a.png)

**Comment by kasperpeulen** [comment]
@MikeMitterer 

Many studies have shown that for reading text, a line length of 50-80 chars is the most readable.
Compare reading this:
![image](https://cloud.githubusercontent.com/assets/1035299/9116544/31046f00-3c65-11e5-9a5d-0db81a85739b.png)

With reading this:
![image](https://cloud.githubusercontent.com/assets/1035299/9116560/458ccea4-3c65-11e5-9b33-ba27c80ffc18.png)

Most people will say the latter is much more readable. Here is an article about this:
http://baymard.com/blog/line-length-readability

I'm not really sure if those studies would translate to also the readability of code. But I guess this is one of the reason dart fmt chooses 80 chars by default. 

However, if you really can't stand the amount of space you waste, you can change this setting. For example do 

```
dartfmt -l 120
```

You can also change the internnal dartfmt formatter of webstorm:
![](http://i.imgur.com/yWfSdEE.png)

![](http://i.imgur.com/M6yNPmN.png)
